### ISSUE TITLE
Mac ssl error

### ISSUE THREAD

**Issue by danielyc** [danielyc/csb#6]
Traceback (most recent call last):
  File "urllib/request.py", line 1318, in do_open
  File "http/client.py", line 1239, in request
  File "http/client.py", line 1285, in _send_request
  File "http/client.py", line 1234, in endheaders
  File "http/client.py", line 1026, in _send_output
  File "http/client.py", line 964, in send
  File "http/client.py", line 1400, in connect
  File "ssl.py", line 407, in wrap_socket
  File "ssl.py", line 814, in __init__
  File "ssl.py", line 1068, in do_handshake
  File "ssl.py", line 689, in do_handshake
ssl.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:777)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main.py", line 538, in <module>
  File "main.py", line 527, in start
  File "main.py", line 413, in __init__
  File "update.py", line 11, in __init__
  File "update.py", line 46, in check_remote_version
  File "urllib/request.py", line 223, in urlopen
  File "urllib/request.py", line 526, in open
  File "urllib/request.py", line 544, in _open
  File "urllib/request.py", line 504, in _call_chain
  File "urllib/request.py", line 1361, in https_open
  File "urllib/request.py", line 1320, in do_open
urllib.error.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:777)>
[20170] Failed to execute script main
logout
Saving session...
...saving history...truncating history files...
...completed.
Deleting expired sessions...none found.

[Process completed]

**Comment by danielyc** [comment]
fixed in new update
